### PR TITLE
JOBSBATCH-213 Partially fixed Batch docs

### PR DESCRIPTION
**Pull request by dimitrystd**

### CODE REVIEW

**Review by PavelLoparev — APPROVED** [review]

**Review by DmitryMasley — APPROVED** [review]

**Comment by DmitryMasley** [comment]
Should we merge it?

**Review by DmitryMasley — APPROVED** [review]
I agree, that `api_common.yaml` should be preferred over the root file.

**Comment by PavelLoparev** [comment]
@DmitryMasley I think we are ok to merge?

**Comment by DmitryMasley** [comment]
Yes, I approved the PR

**Pull request merged**
