### PR TITLE
DELTA-1282 update upload context api

### PR DESCRIPTION
**Pull request by MihailTymoshenko**

### CODE REVIEW

**Comment by MihailTymoshenko** [comment]
Screenshot 2021-04-29 at 09 38 15

**Comment by MihailTymoshenko** [comment]
Screenshot 2021-04-29 at 09 39 18

**Comment by MihailTymoshenko** [comment]
Screenshot 2021-04-29 at 09 38 15
Screenshot 2021-04-29 at 09 39 18
Screenshot 2021-04-29 at 09 40 25
Screenshot 2021-04-29 at 09 41 08
Screenshot 2021-04-29 at 09 41 27
Screenshot 2021-04-29 at 09 41 45
Screenshot 2021-04-29 at 09 42 00
Screenshot 2021-04-29 at 09 42 13

**Comment by rischenko** [comment]
https://api-reference.smartling.com/preview/delta-1282-update-upload-context-api/#operation/uploadNewVisualContext

**Review by vbarhatov — CHANGES_REQUESTED** [review]
I've updated the Google document. Please check it

**Comment by MihailTymoshenko** [comment]
> I've updated the Google document. Please check it
updated

**Review by vbarhatov — APPROVED** [review]
checked

**Review by dsavchenko-sm — COMMENTED** [review]
👍

**Pull request merged**
